### ISSUE TITLE
Creating a new repo via gobbs?

### ISSUE THREAD

**Issue by Foryah** [gfleury/gobbs#1]
Would be nice to be able to create a new repository via gobbs. Maybe something like: 
```
gobbs repo add
```

If the command could create the repo then return the url that can be fed into `git remote add origin` then it would be amazing :)

**Comment by gfleury** [comment]
@Foryah , 
Available on last release!

`gobbs -H http://localhost:7990 -u admin -p AdminPass -P PROJ repo create newrepo4
+----+----------+---------------------------------------------+-----------+
| ID |   SLUG   |                    LINKS                    |  STATUS   |
+----+----------+---------------------------------------------+-----------+
| 14 | newrepo4 | http:                                       | Available |
|    |          | http://localhost:7990/scm/proj/newrepo4.git |           |
|    |          | ssh:                                        |           |
|    |          | ssh://git@localhost:7999/proj/newrepo4.git  |           |
+----+----------+---------------------------------------------+-----------+`

**Comment by Foryah** [comment]
Awesome!
