### ISSUE TITLE
Configuration using environment variables

### ISSUE THREAD

**Issue by jfroche** [gfleury/gobbs#2]
Hello,

I tried to find a way to tell viper to use environment variable to configure parameters. I see that you are using `Viper.AutomaticEnv` but it doesn't seem to be taken into account. This https://github.com/spf13/viper/issues/584 might be related ?

Our usecase is that we would like to use `gobbs` into our CI but we would prefer to configure it using environment variable.

Thanks for this nice project !

**Comment by gfleury** [comment]
Hey @jfroche, 
So, there is some hacks/workarounds done in place to get other pieces of it working, that actually broke the ability of using ENV vars, but it should not be very difficult to get it working. I did a small hacky way on #3 , see if this helps. If so I can create a release.

**Comment by gfleury** [comment]
@jfroche Let me know if it does work as expected.
